import { StyleSheet } from "react-native";

export default StyleSheet.create({
  appView: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#f5f9f6",
  },
  title: {
    fontWeight: "bold",
    fontSize: 28,
    textAlign: "center",
    margin: 20,
    color: "#0f172a",
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "#6b7280",
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  button: {
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    padding: 4,
  },
  listItem: {
    backgroundColor: "#ffffff",
    padding: 14,
    marginVertical: 4,
    marginHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#080f1e",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  listItemText: {
    fontSize: 18,
    color: "#0f172a",
    fontWeight: "600",
  },
  listItemSub: {
    fontSize: 13,
    color: "#6b7280",
    marginTop: 2,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#00b894",
    marginTop: 12,
    marginHorizontal: 16,
  },
  detailValue: {
    fontSize: 16,
    marginHorizontal: 16,
    marginTop: 2,
    color: "#0f172a",
  },
  image: {
    width: 300,
    height: 300,
    alignSelf: "center",
    marginVertical: 12,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#00b894",
  },
  searchInput: {
    fontSize: 16,
    height: 44,
    borderWidth: 1,
    borderColor: "#00b894",
    borderRadius: 8,
    paddingHorizontal: 12,
    margin: 12,
    backgroundColor: "#ffffff",
    color: "#0f172a",
  },
  aboutText: {
    fontSize: 16,
    textAlign: "center",
    marginVertical: 8,
    color: "#0f172a",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    marginBottom: 16,
    shadowColor: "#080f1e",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 6,
    color: "#0f172a",
  },
  cardBody: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 10,
  },
});
